file_name_skips:
  -
file_extension_skips:
  -
directory_skips:
  -
process_kill_names:
  -
groups:
  - group: BlackBasta
    extension_method: append
    extensions:
      - basta
      - '%R%R%R%R%R%R%R%R%R' #% %RAN% indicates random letter or digit
    cipher: XChaCha20
    notes:
      - readme.txt
      - instructions_read_me.txt
    note: |
      ATTENTION!
      Your network has been breached and all data was encrypted.  Please contact us at:
      
      
      bastad5huzwkepdixedg2gekg7jk22ato24zyllp6lnjx7wdtyctgvyd.onion
      
      
      Login ID: %R%R%R%R%R%R%R%R-%R%R%R%R-%R%R%R%R-%R%R%R%R-%R%R%R%R%R%R%R%R%R%R%R%R
      
      *!* To access .onion website download and install Tor Browser at:
      
        https://www.torproject.org/ (Tor Browser is not related to us)
      
      *!* TO restore all your PCs and get your network working again, follow these instructions:
      
      - Any attempts to modify, decrypt or rename the files will lead to its fatal corruption.  It doesn't matter, who are 
      trying to do this, either it will be your IT guys or a recovery agency.
      
      Please follow these simple rules to avoid data corruption:
      
      - Do not modify, rename or delete files.  Any attempts to modify, decrypt ot rename the files will lead to its fatal corruption.
      
      - Do not hire a recovery company.  They can't decrypt without the key.
      They also don't care about your business.  They believe that they are good negotiators, but it is not.  
      They usually fail.  So speak for yourself.
      
      Waiting you in a chat.
  - group: RansomHub   # Technically RansomHub has been observed using ECC/ECDH for asym but we use RSA https://www.trendmicro.com/vinfo/us/security/news/ransomware-spotlight/ransomware-spotlight-ransomhub
    extension_method: append  # RSA achieves similar effect anyways
    extensions:
      - basta
      - '%R%R%R%R%R%R%R%R%R' #% %RAN% indicates random letter or digit
    cipher: aes256
    notes:
      - How To Restore Your Files.txt
    note: |
      ATTENTION!
      Your network has been breached and all data was encrypted.  Please contact us at:
      
      
      bastad5huzwkepdixedg2gekg7jk22ato24zyllp6lnjx7wdtyctgvyd.onion
      
      
      Login ID: %R%R%R%R%R%R%R%R-%R%R%R%R-%R%R%R%R-%R%R%R%R-%R%R%R%R%R%R%R%R%R%R%R%R
      
      *!* To access .onion website download and install Tor Browser at:
      
        https://www.torproject.org/ (Tor Browser is not related to us)
      
      *!* TO restore all your PCs and get your network working again, follow these instructions:
      
      - Any attempts to modify, decrypt or rename the files will lead to its fatal corruption.  It doesn't matter, who are 
      trying to do this, either it will be your IT guys or a recovery agency.
      
      Please follow these simple rules to avoid data corruption:
      
      - Do not modify, rename or delete files.  Any attempts to modify, decrypt ot rename the files will lead to its fatal corruption.
      
      - Do not hire a recovery company.  They can't decrypt without the key.
      They also don't care about your business.  They believe that they are good negotiators, but it is not.  
      They usually fail.  So speak for yourself.
      
      Waiting you in a chat.
    
