// Code generated by https://github.com/abakum/embed-encrypt; DO NOT EDIT.

package main

import (
	"embed"
	"github.com/abakum/embed-encrypt/encryptedfs"
)

//go:embed key.enc
var key []byte

//go:embed "config.yaml.enc"
var configFileEnc embed.FS

func init() {
	configFile = encryptedfs.InitFS(configFileEnc, key)
}
